# Data Sources
As our team found out that our common interest is the bike-sharing system, we decided to interpret the detailed time and location records such as the travel duration and locations. Then, we searched online for data generated by the bike-sharing programs. The original source of the dataset we agreed to work is the two-year historical log corresponding to years 2011 and 2012 from the Capital Bikeshare system, Washington D.C., USA which is 
publicly available in http://capitalbikeshare.com/system-data. As quoted from the website, the data includes:
- Duration – Duration of trip
- Start Date – Includes start date and time
- End Date – Includes end date and time
- Start Station – Includes starting station name and number
- End Station – Includes ending station name and number
- Bike Number – Includes ID number of bike used for the trip
- Member Type – Indicates whether user was a "registered" member (Annual Member, 30-Day Member or Day Key Member) or a "casual" rider (Single Trip, 24-Hour Pass, 3-Day Pass or 5-Day Pass)

Besides, we wanted to integrate into it other useful information such as the weather conditions and holiday schedules. Bike-sharing rental process is highly correlated with the environmental and seasonal settings. For instance, weather conditions, precipitation, day of week, season, hour of the day, and etc. can affect the rental behaviors. These data were collected from https://www.ncdc.noaa.gov/, http://dchr.dc.gov/page/holiday-schedule, and http://www.freemeteo.com. We merged the corresponding weather and seasonal information with the bike-sharing data over all record on a daily basis.