---
title: "RQ_draft"
author: "Rui Qin"
date: "12/2/2020"
output: html_document
---
```{r}
# download bike sharing data
if (!file.exists("data")) {
  dir.create(file.path(getwd(), "data"))
}
address = "https://s3.amazonaws.com/capitalbikeshare-data/201801-capitalbikeshare-tripdata.zip"
download.file(address, file.path("data", basename(address)))
f = unzip(file.path("data", basename(address)), "201801_capitalbikeshare_tripdata.csv", exdir=file.path("data"))
df = read.csv(f)

address = "https://s3.amazonaws.com/capitalbikeshare-data/201907-capitalbikeshare-tripdata.zip"
download.file(address, file.path("data", basename(address)))
unzip(file.path("data", basename(address)), "201907-capitalbikeshare-tripdata", exdir=file.path("data"))
file.rename(file.path("data", "201907-capitalbikeshare-tripdata"), file.path("data", "201907-capitalbikeshare-tripdata.csv"))
df = rbind(df, read.csv("data/201907-capitalbikeshare-tripdata.csv"))
for (y in c("2018", "2019")) {
  for (m in 1:12) {
    if (y == "2018" && m == 1) {
      next
    }
    if (y == "2019" && m == 7) {
      next
    }
    address = sprintf("https://s3.amazonaws.com/capitalbikeshare-data/%s%02d-capitalbikeshare-tripdata.zip", y,m)
    download.file(address, file.path("data", basename(address)))
    f = unzip(file.path("data", basename(address)), gsub(".zip", ".csv", basename(address)), exdir=file.path("data"))
    df = rbind(df, read.csv(f))
  }
}

# drop unnecessary variables
df = df %>% select(c(1, 2, 3, 9))

# create variables regarding date and time
t_start = strptime(as.character(df$Start.date), "%Y-%m-%d %H:%M:%S")
t_end = strptime(as.character(df$End.date), "%Y-%m-%d %H:%M:%S")
df$start_date = as.character(date(t_start))
df$start_year = year(t_start)
df$start_month = month(t_start, label = TRUE)
df$start_day = day(t_start)
df$start_hour = hour(t_start)
df$start_minute = minute(t_start)
df$start_second = second(t_start)
df$end_date = as.character(date(t_end))
df$end_year = year(t_end)
df$end_month = month(t_end, label = TRUE)
df$end_day = day(t_end)
df$end_hour = hour(t_end)
df$end_minute = minute(t_end)
df$end_second = second(t_end)
#df = df %>% select(!c("Start.date", "End.date"))

# read temperature data
# change date format
temp = read.csv("temp_data/temp.csv")
temp$DATE = format(strptime(as.character(temp$DATE), "%m/%d/%Y"), "%Y-%m-%d")

# merge two data frames on date
df = left_join(df, temp, by = c("start_date" = "DATE"))

# add the variable: day of week
df$weekday = weekdays(as.Date(df$start_date, "%Y-%m-%d"))

# holidays of 2011 and 2012
holidays = c("2018-01-01", "2018-01-15", "2018-02-19", "2018-04-16", "2018-05-28", "2018-07-04",
             "2018-09-03", "2018-10-08", "2018-11-12", "2018-11-22", "2018-12-25", "2019-01-01",
             "2019-01-21", "2019-02-18", "2019-04-13", "2019-05-27", "2019-07-04", "2019-09-02",
             "2019-10-14", "2019-11-11", "2019-11-28", "2019-12-25")

# add a variable to check if the bike sharing happened on a workday
df$holidays = df$start_date %in% holidays
df$workdays = !(df$weekday %in% c("Saturday", "Sunday") | df$holidays)
df$workdays = recode_factor(as.factor(df$workdays), "TRUE" = "Workdays", "FALSE" = "Non-workdays")
df = df %>% select(!c("weekday", "holidays"))
```


```{r}
df %>% 
  group_by(start_hour) %>% 
  count() %>% 
  mutate(Time = factor(sprintf("%s:00",start_hour))) %>%
  mutate(Time = fct_rev(Time)) %>%
  ggplot(aes(x=Time, y=n/24)) +
    geom_bar(stat="identity") +
    ylab("Number of riders") +
    coord_flip()
```


```{r}
df[df$Member.type %in% c("Member", "Casual"),] %>% 
  group_by(Member.type, start_hour) %>% 
  count() %>% 
  mutate(Time = factor(sprintf("%s:00",start_hour))) %>%
  mutate(Time = fct_rev(Time)) %>%
  ggplot(aes(x=Time, y=n/24)) +
    geom_bar(stat="identity") +
    facet_wrap(.~Member.type) +
    ylab("Number of riders") +
    coord_flip()
```
```{r}
df[df$Member.type %in% c("Member", "Casual"),] %>% 
  group_by(Member.type, start_hour) %>% 
  count() %>% 
  mutate(Time = factor(sprintf("%s:00",start_hour))) %>%
  mutate(Time = fct_rev(Time)) %>%
  mutate(n = ifelse(Member.type == "Member", n, -n)) %>%
  ggplot(aes(x=Time, y=n/24, fill=Member.type)) + 
    geom_bar(stat="identity") +
    coord_flip() +
    scale_y_continuous(name = "Number of riders", 
                       breaks = seq(-5000,30000,5000), 
                       limits = c(-5000, 30000),
                       labels = abs(seq(-5000,30000,5000)))
```

```{r}
df %>%
  group_by(start_month) %>%
  count() %>%
  ggplot(aes(start_month, n/2)) +
  geom_bar(stat="identity") +
  xlab("Month")
```

